name = "airstore"
main = "src/app.js"
compatibility_date = "2023-09-29"
node_compat = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "airstore"
database_id = "30af52f2-30fa-405f-b3f6-81481cdce706"
